[package]
name = "recovery"
type = "contract"
authors = [""]
compiler_version = ">=1.0.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v3.0.0-devnet.5", directory="noir-projects/aztec-nr/aztec" }
token = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v3.0.0-devnet.5", directory="noir-projects/noir-contracts/contracts/app/token_contract" }
wormhole = { git="https://github.com/NethermindEth/wormhole", tag="v3.0.0-flat-no-fees.devnet.5", directory="aztec/contracts" }